# Generated by Django 4.2 on 2023-05-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0002_alter_category_category_img'),
        ('groceryproducts', '0002_grocery_alter_category_category_img'),
    ]

    operations = [
    ]
