# Generated by Django 4.2 on 2023-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0003_merge_20230511_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.FileField(default=None, max_length=250, null=True, upload_to='product_images/')),
                ('product_title', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
            ],
        ),
    ]
